# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/exhdd/tomorning_dataset/examples/DL_worker

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/exhdd/tomorning_dataset/examples/DL_worker

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/exhdd/tomorning_dataset/examples/DL_worker/CMakeFiles /mnt/exhdd/tomorning_dataset/examples/DL_worker/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/exhdd/tomorning_dataset/examples/DL_worker/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named DPWorker

# Build rule for target.
DPWorker: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 DPWorker
.PHONY : DPWorker

# fast build rule for target.
DPWorker/fast:
	$(MAKE) -f CMakeFiles/DPWorker.dir/build.make CMakeFiles/DPWorker.dir/build
.PHONY : DPWorker/fast

DeepFeatureExtractor.o: DeepFeatureExtractor.cpp.o
.PHONY : DeepFeatureExtractor.o

# target to build an object file
DeepFeatureExtractor.cpp.o:
	$(MAKE) -f CMakeFiles/DPWorker.dir/build.make CMakeFiles/DPWorker.dir/DeepFeatureExtractor.cpp.o
.PHONY : DeepFeatureExtractor.cpp.o

DeepFeatureExtractor.i: DeepFeatureExtractor.cpp.i
.PHONY : DeepFeatureExtractor.i

# target to preprocess a source file
DeepFeatureExtractor.cpp.i:
	$(MAKE) -f CMakeFiles/DPWorker.dir/build.make CMakeFiles/DPWorker.dir/DeepFeatureExtractor.cpp.i
.PHONY : DeepFeatureExtractor.cpp.i

DeepFeatureExtractor.s: DeepFeatureExtractor.cpp.s
.PHONY : DeepFeatureExtractor.s

# target to generate assembly for a file
DeepFeatureExtractor.cpp.s:
	$(MAKE) -f CMakeFiles/DPWorker.dir/build.make CMakeFiles/DPWorker.dir/DeepFeatureExtractor.cpp.s
.PHONY : DeepFeatureExtractor.cpp.s

dp_main.o: dp_main.cpp.o
.PHONY : dp_main.o

# target to build an object file
dp_main.cpp.o:
	$(MAKE) -f CMakeFiles/DPWorker.dir/build.make CMakeFiles/DPWorker.dir/dp_main.cpp.o
.PHONY : dp_main.cpp.o

dp_main.i: dp_main.cpp.i
.PHONY : dp_main.i

# target to preprocess a source file
dp_main.cpp.i:
	$(MAKE) -f CMakeFiles/DPWorker.dir/build.make CMakeFiles/DPWorker.dir/dp_main.cpp.i
.PHONY : dp_main.cpp.i

dp_main.s: dp_main.cpp.s
.PHONY : dp_main.s

# target to generate assembly for a file
dp_main.cpp.s:
	$(MAKE) -f CMakeFiles/DPWorker.dir/build.make CMakeFiles/DPWorker.dir/dp_main.cpp.s
.PHONY : dp_main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... DPWorker"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... DeepFeatureExtractor.o"
	@echo "... DeepFeatureExtractor.i"
	@echo "... DeepFeatureExtractor.s"
	@echo "... dp_main.o"
	@echo "... dp_main.i"
	@echo "... dp_main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

